### ISSUE TITLE
Cannot load PayPal section from web.config

### ISSUE THREAD

**Issue by pageroller** [paypal/PayPal-NET-SDK#101]
Hello,

I am trying to set up PayPal in a new MVC5 web application.

Your documentation doesn't state that you need to add in the `<accounts />` element from the `<paypal />` section (only `<settings />`) so I had to dig through the code to add it in.

Sample code should look like this:

````xml
	<configSections>
		<section name="paypal" type="PayPal.SDKConfigHandler, PayPal" />
	</configSections>
	<paypal>
		<settings>
			<add name="mode" value="sandbox" />
			<add name="clientId" value="" />
			<add name="clientSecret" value="" />
		</settings>
		<accounts>
			<account apiUsername="" apiPassword="" apiSignature="" />
		</accounts>
	</paypal>
````

When `<accounts />` isn't there it throws this error:

````
Unable to load 'paypal' section from *.config: Required attribute 'accounts' not found.
````

I'm now getting this really strange error when attempting to call ConfigManager.Instance.GetProperties(); The error message is: 
````
Unable to load 'paypal' section from *.config: An error occurred creating the configuration section handler for paypal: [C:\Users\Peter\AppData\Local\Temp\Temporary ASP.NET Files\vs\324c5a82\84589666\assembly\dl3\c1001f82\1f0b2ff7_8494d001\PayPal.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations. 
````

Stack trace:

````
[ConfigException: Unable to load 'paypal' section from *.config: An error occurred creating the configuration section handler for paypal: [C:\Users\Peter\AppData\Local\Temp\Temporary ASP.NET Files\vs\324c5a82\84589666\assembly\dl3\c1001f82\1f0b2ff7_8494d001\PayPal.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations. (C:\Users\Peter\Source\Workspaces\ROA101.01 - American Sniper\VR.WebApp\web.config line 10)]
   PayPal.Api.ConfigManager..ctor() +149
   PayPal.Api.ConfigManager.get_Instance() +92
   VR.WebApp.Providers.PayPalProvider.Create(Decimal dollarAmount, String returnUrl) i
````

Do you have any idea on what is going on?

**Comment by pageroller** [comment]
Seems like to only have broken in version 1.4.3. Rolling back to version 1.4.2 works ok for me.

**Comment by jziaja** [comment]
Thanks for reporting this, @pageroller.  It looks like this might be related to some changes that were made with respect to declaring certain classes as `internal` instead of `public`.  I'll do some more testing and get this fixed ASAP.

Also, the `<accounts>` config section is only used by the older Classic SDKs and is not used by this SDK.  Are you using this SDK along with one of the Classic SDKs?

**Comment by pageroller** [comment]
The error disappeared when I downgraded it, so I think it may have been just something else triggering it internally.

**Comment by jziaja** [comment]
I wonder if this could have to do with the fact that our build process performs the strong-name signing on the PayPal.dll file as a post-build process.  The `InternalsVisibleTo` assembly attribute was added so the unit test project could still test the `internal` classes.  

It may be time to add the SNK as part of the project here on GitHub as it's beginning to cause more problems (along with complicating the build process).  This is also what Microsoft recommends [here](https://msdn.microsoft.com/en-us/library/wd40t7ad.aspx) for open source projects:

> If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system.

**Comment by jziaja** [comment]
@pageroller would you mind sharing how you have your project setup along with what your web.config file looks like?  I tried reproducing this with both the Samples project here and a newly-created project, but I'm not seeing the exception thrown in either one.  I also tried running the projects both with and without an `<accounts>` section in the config, and it was able to be loaded just fine in each case when calling `ConfigManager.Instance.GetProperties()`.

**Comment by VickyMahir** [comment]
I have same issue while calling ConfigManager.Instance.GetProperties().
I have use PayPal.NET SDK version 1.4.3 .

So any one please tell me how to solve this issue?

**Comment by jziaja** [comment]
@VickyMahir, the current solution if you're experiencing this issue is to downgrade to version 1.4.2.  Currently, I'm unable to reproduce the issue on my end so any details you can help provide would be great.  

The following information should help in tracking down the cause of this bug:
* What does the `<paypal>` your application's **web.config** look like (please remove any live credentials)?
* What does the `<Reference>` definition in your project's **.csproj** file look like that references PayPal.dll?
* Are you using this project in combination with one of the PayPal Classic SDKs (e.g. [Merchant SDK](https://github.com/paypal/merchant-sdk-dotnet), [Adaptive Payments SDK](https://github.com/paypal/adaptivepayments-sdk-dotnet), [Adaptive Accounts SDK](https://github.com/paypal/adaptiveaccounts-sdk-dotnet), [Permissions SDK](https://github.com/paypal/permissions-sdk-dotnet), [Invoice SDK](https://github.com/paypal/invoice-sdk-dotnet))?

**Comment by VickyMahir** [comment]
@jziaja , I have resolved issue in version 1.4.3 using below code so is it ok?

var apiContext = new APIContext(token);
                apiContext.Config = config; //PayPal.Api.ConfigManager.Instance.GetProperties();

                // Define any custom configuration settings for calls that will use this object.
                apiContext.Config["connectionTimeout"] = "10000"; // Quick timeout for testing purposes

                //// Define any HTTP headers to be used in HTTP requests made with this APIContext object
                if (apiContext.HTTPHeaders == null)
                {
                    apiContext.HTTPHeaders = new Dictionary<string, string>();
                    apiContext.HTTPHeaders.Add("apiUsername", auth.Username);
                    apiContext.HTTPHeaders.Add("apiPassword", auth.Password);
                    apiContext.HTTPHeaders.Add("apiSignature", apiSignature);
                }

**Comment by jziaja** [comment]
@VickyMahir, what is `config` set to in your code?

**Comment by VickyMahir** [comment]
@jziaja , Nothing in config file

**Comment by jziaja** [comment]
I meant on this line in the code you posted above:

````csharp
apiContext.Config = config; //PayPal.Api.ConfigManager.Instance.GetProperties();
````

What is the value of `config` here?  Is it null or set to something else?  

Also, are you using this SDK in combination with one of the Classic SDKs?

**Comment by VickyMahir** [comment]
@jziaja , Value of config is 

                var config = new Dictionary<string, string>();
                config.Add("mode", "sandbox");
                config.Add("clientId", clientID);
                config.Add("clientSecret", clientSecret);

I am using only PayPal NET SDK not any other SDK in my application.

**Comment by jziaja** [comment]
Thanks @VickyMahir.  If you can reproduce this issue in a newly-created project, would you mind emailing me the zipped-up project files at jziaja@paypal.com?

**Comment by pageroller** [comment]
Sorry for the delay - I've emailed you a copy of the solution with the issue replicated.

**Comment by kenney777** [comment]
@pageroller do you have .net framework 4.6 RC installed? if you check the registry @ HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full and if the "release"  key has a value of 393273 then you probably installed VS 2015. After removing the 4.6 RC from my system and reinstalling 4.5.1 it fixed the issue for me with the 1.4.3 nuget package.

**Comment by jziaja** [comment]
Thanks a **ton** to @kenney777 for discovering the issue with .NET 4.6 RC. :+1: 

[Another developer on StackOverflow](http://stackoverflow.com/questions/30534590/unable-to-load-paypal-section-from-your-config) also encountered this issue and was able to resolve it by uninstalling .NET 4.6 RC.

The root cause for the issue looks to be that .NET 4.6 RC is a bit stricter when executing a strong-name signed assembly with respect to how the assembly, class, and property attributes are defined in the assembly.  Regarding this SDK, the .NET framework's behavior has changed in .NET 4.6 RC regarding the following attributes:

  *  Specifying the assembly attribute `InternalsVisibleTo()` in a strong-name signed assembly that is missing a `PublicKey` declaration will throw an error.  Currently, we have a post-build step prior to publishing that strong-name signs the PayPal.dll assembly with a private SNK.  By default, the project isn't setup to use an SNK, which means the [`InternalsVisibleTo()`](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Properties/AssemblyInfo.cs#L45) declaration is intentionally missing a `PublicKey` reference to the **PayPal.Tests** project.  The reason we didn't discover this issue internally prior to release is we currently run our tests on a system whose highest, installed .NET framework is 4.5.1.

  * The `IsRequired` parameter of a `ConfigurationProperty` property attribute is honored in .NET 4.6 RC, whereas it looks to have been ignored in previous versions of .NET.  The place where this is causing a problem is for the [`<accounts>` config property](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Manager/SDKConfigHandler.cs#L21).  This property was intentionally left in for compatibility reasons with the Classic SDKs and is not used by this SDK.  For this reason, I'm going to change its value to `false` to make it optional for this SDK.

We're currently discussing internally what a better strategy might be on the strong-name signing.  I know there's [a](http://stackoverflow.com/a/396159/3864867) [lot](http://stackoverflow.com/a/886024/3864867) [of](http://stackoverflow.com/a/396146/3864867) [opinions](http://stackoverflow.com/a/1831282/3864867) flying around the open-source .NET world regarding whether or not an open source project should publish its private key.  [Microsoft suggests it for open source projects](https://msdn.microsoft.com/en-us/library/wd40t7ad%28v=vs.110%29.aspx), and while I don't view the strong-name key we use as a means of security, I do view it as a means of establishing  a level of trust with developers using it.  For that reason, I'm going to investigate using a separate, publicly-available key that will be published here on GitHub, while our internal build process will still use our own, private key.  I'll be working on this setup over on the [issue-101](https://github.com/paypal/PayPal-NET-SDK/tree/issue-101) branch if you'd like to see the changes (it's currently missing the public key as I play around with the project settings and).

Until this change is finalized (which I'll use this thread to provide updates on), please feel free to voice your opinion of how the strong-name signing should be handled for an open source project.

Thanks! :+1:

**Comment by Jaans** [comment]
Regarding strong-name signing - I agree with your approach. This may be open source, but I for one would definitely want to know whether the binary I'm using is signed by PayPal or someone else who may have "fiddled" with it (given it's accessible to everyone). Users who build the SDK themselves, can provide their own key for strong naming.
Obviously this is IMO.

**Comment by jziaja** [comment]
Would yall mind trying out this beta release for version 1.4.4 and see if it resolves the .NET 4.6 RC compatibility issue?
* [GitHub](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.4.4-beta)
* [NuGet](https://www.nuget.org/packages/PayPal/1.4.4-beta)

For NuGet, you can run the following command in the Package Manager console to get the 1.4.4 beta:

````
PM> Install-Package PayPal -Pre
````

I tested this build on Windows 8.1 with .NET 4.6 RC.  Using version 1.4.3, I was able to reproduce the error.  Using 1.4.4 beta, the error went away, and I was able to successfully load the config (without the need for an `<accounts>` section as well).

Thanks!

**Comment by hmemcpy** [comment]
Had the same issue with 1.4.3 (rolling back to 1.4.2 helped!)
Confirming 1.4.4 works - the issue is resolved! (Using VS2015 RC)
Thank you @jziaja!

**Comment by jziaja** [comment]
Thanks for confirming, @hmemcpy!  I'll get this officially released by the end of today (want to run another round of tests on it first).

**Comment by jziaja** [comment]
**1.4.4** is now released!
* [GitHub](https://github.com/paypal/PayPal-NET-SDK/releases/tag/v1.4.4)
* [NuGet](https://www.nuget.org/packages/PayPal/1.4.4)

Thanks again to everyone here for all your help! :+1:

**Comment by sandipgend** [comment]
i used paypal 1.4.0 dll but it give me following error

Unable to cast object of type 'PayPal.SDKConfigHandler' to type 'System.Xml.XmlNode

**Comment by ppmtscory** [comment]
@sandipgend this issue is very old and may or may not be the same root cause for your issue.  With that said, please open a new issue with any/all specific details that you can provide.
