### ISSUE TITLE
Creating payments: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by rivdiv** [paypal/PayPal-NET-SDK#117]
Starting 3 days ago, throughout the day, we've been getting 401 Unauthorized errors when trying to create, charge payments etc - all API transactions - it seems sometimes it works and sometimes it doesn't. I did notice a pattern where I stop getting the errors at a certain time every night.

(On PayPal's SSL upgrade they mentioned SDKs don't need to be updated but I did update to the latest version just in case the error had to do with it, but it did not help.)

The exact error I'm getting is: Exception in HttpConnection Execute: Invalid HTTP response The remote server returned an error: (401) Unauthorized.

Because the errors are on and off, this doesn't sound like a coding issue to me, but I'm posting it here just to be sure it's not an integration / API update issue of some sort...thanks.

**Comment by jziaja** [comment]
Hi @rivdiv, there was an issue recently with the identity service that should be fixed now.  Closing this issue since it's not directly related to using the SDK.  For issues related to API errors, we recommend contacting the [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask/) team directly.
