### ISSUE TITLE
IPN's for recurring_payment_profile_cancel not sent when payment method is PayPal in Sandbox

### ISSUE THREAD

**Issue by ckilyk** [paypal/PayPal-NET-SDK#127]
I noticed something odd - if I call the Agreement.Cancel method from the SDK, and pass in the Recurring Profile Id that used PayPal as the payment method, it seems the Sandbox is not sending IPN's for those messages.  If the payment was a credit card the recurring_payment_profile_cancel message comes through consistently.

Should this be sending that IPN message when the payment method was a paypal account?

**Comment by ppmtscory** [comment]
First off, apologies for the delay here.  Secondly, is this still an issue for you?  As far as I know (I'll have to run some tests) you should receive a cancellation IPN.  I ask if it's still an issue because there may have been some IPN issues around this time that may have been causing it.  Let me know!

**Comment by xiaoleih41** [comment]
Close due to inactivity.
