### ISSUE TITLE
404 Not Found errors for payments made by foreign customers

### ISSUE THREAD

**Issue by tiffaa** [paypal/PayPal-NET-SDK#144]
Hello,

we are using the SALE APi to look up and refund completed payments. Recently, we recived a couple of 404 errors while looking up a sale:

`Sale s = Sale.Get(accessToken, transactionId);`
`>> The remote server returned an error: (404) Not Found.`

we tried to identify the problem and noticed that all payments were made by foreign customers. (non german, we based this on their email adress)
Currency shouldn't be an issue because all payments were made in EUR. Payments by german customers are working fine.

Are there any limiations regarding payments made by customers from foreign countrys? Are there any settings we have to use so that we can look up those payments (and later on refund them?)

Thanks in advance.

**Comment by pp-randy** [comment]
@tiffaa would you be able to provide a debug-id from either the response body or the header?  I'm not aware of limitations on EUR currency but I'm happy to look into this further.

**Comment by tiffaa** [comment]
sure thing!

this is one of the latest payments from today:

> 
"name":"INVALID_RESOURCE_ID",
"message":"The requested resource ID was not found",
"information_link":"https://developer.paypal.com/docs/api/#INVALID_RESOURCE_ID",
"debug_id":"62fbeb2aaff14"

> 
PROXY_SERVER_INFO: host=slcjavapapi3037b.slc.paypal.com;threadId=279
Paypal-Debug-Id: 62fbeb2aaff14
CORRELATION-ID: 62fbeb2aaff14
Content-Language: *
Content-Length: 189
Content-Type: application/json
Date: Wed, 10 Feb 2016 15:43:56 GMT
Server: Apache-Coyote/1.1

thank you for looking into this!

**Comment by ppmtscory** [comment]
@tiffaa you are getting that error because that transaction that you are trying to look up was not processed via REST APIs.  The REST API look up calls are only for transactions processed via REST API.  Since this was not, there's no Payment ID (resource ID) to be found.  For looking up transactions that were processed via Classic API, you'll need to use [GetTransactionDetails](https://developer.paypal.com/docs/classic/api/merchant/GetTransactionDetails_API_Operation_NVP/)
