### ISSUE TITLE
sandbox rest api return INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by DukeNuken** [paypal/PayPal-NET-SDK#152]
Hello. 

I am using last version of paypal lib 1.7.3.0 and when I try create new payment I see an error like this

> {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"e7b19d3ac5d56"}

Why it happends? That code work before and still working for production. 

Duke

**Comment by ppmtscory** [comment]
Hi all, sandbox appears to be experiencing some downtime. We're tracking the issue over at [paypal/PayPal-PHP-SDK#531](https://github.com/paypal/PayPal-PHP-SDK/issues/531), so I'm going to close this one as a duplicate so that we don't have multiple threads. We'll provide back information as we can there.
