### ISSUE TITLE
Unable to do DirectPayment

### ISSUE THREAD

**Issue by NormTheThird** [paypal/PayPal-NET-SDK#262]
Is it possible to do DirectPayments through this api?

**Comment by pp-randy** [comment]
You can create payments with credit cards with this API https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentWithCreditCard.aspx.cs.

However, only US and UK accounts are supported.   Otherwise, this is the SDK you are looking for which directly supports DirectPayment API https://github.com/paypal/merchant-sdk-dotnet.

**Comment by xiaoleih41** [comment]
Close this ticket due to inactivity. Please resubmit if you have any further question.
