### ISSUE TITLE
Using PayPal.SDK.NETCore or PayPal-NET-SDK Beta 2.0

### ISSUE THREAD

**Issue by JORGEGO** [paypal/PayPal-NET-SDK#334]
Dear,
I want to integrated PayPal in my Xamarin.Form .Net Standard 2.0 application mobile. 
After looking in many places, I ve just arrived here.
First I downloaded the PayPal.SDK.NETCore 1.9.2 nugget package, but not source code was on the GitHub, from branch 1.9.1 jump to beta 2.0... Then I have decided to test all the possibilities download source from this branch.
Let met ask few questions:

1. Do you believe it is the best package to integrated PayPal on Xamarin.Forms with .NET Standard 2.0?
2. There are some place with samples to use from this branch. or samples are the same as 1.9.1 branch
3. Any date to create release version?

Thanks

**Comment by xiaoleih41** [comment]
We will get back to you on your questions.

**Comment by bluk** [comment]
This SDK is only intended for server side SDK usage and is not intended for a mobile application. Due to the SDK requiring your client ID and client secrets, if your mobile app was reverse engineered, someone could get your credentials and act as your merchant account (e.g. refund all your payments). So you should not use this SDK directly in a mobile app. You could use this SDK in a server side app and have your mobile app communicate with the server side app.

Regarding your other questions:

The latest non-beta official version is [1.9.1](https://www.nuget.org/packages/PayPal) for this PayPal REST API SDK. Other third parties may have other versions of the REST API SDK but they are unsupported by PayPal and used at your own risk.

The 2.0 beta is where new features and APIs will be developed. The README has information on how to make a request, and you can review the branch for some basic examples. The samples from the 1.9.1 will not work as-is but can give you an idea about what the fields are. The 2.0-beta gives more control of the request and response to the PayPal REST APIs and should be a simpler integration. We will give at least a few weeks to shake out any issues for the 2.0 beta before declaring it to be the official version.

We appreciate any feedback you have on the beta, so if you have any issues, please feel free to leave a comment or open a new issue. Thanks.
