### ISSUE TITLE
PLEASE asp.net Core 2.0 WORKING example needed...

### ISSUE THREAD

**Issue by sipi41** [paypal/PayPal-NET-SDK#355]
I'm trying to give Paypal a try, I'm a newbie in asp.Net Core 2.0 but I think I can understand most of the programming structure.  I did follow the steps: 1) did create an account on Sandbox with credential and secrete... so I came to create a brand new asp.net Core 2.0 app, and installed the Paypal 2.0.0-rc2, so basically I have the whole thing right??

The example is impossible to follow as it was built for another version of .net... maybe?  For example, it talks about creating a configuration file web.config or app.config... but in core 2.0 its called appsettings.json but, that's not a huge problem!

the real **Problem** begins when we start doing C#... for example it says I should call **using PayPal.Api;** at the top of the page but the app respond with an error saying: **"The type or namespace Api does not exist in the namespace Paypal, are you missing a reference?"**, according to what I have installed, we only have 2 options, using Paypal.Core or using Paypal.v1...

Would you **please** provide with a real working example using asp.net Core 2.0 MVC 6 ? because maybe for an experienced person this is a piece of cake but for me... well... 

Thank you for your help and patience!

**Comment by xiaoleih41** [comment]
Just want to make sure you have downloaded the right SDK version for  .NET core. https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta

**Comment by sipi41** [comment]
Yes... I have downloaded the new beta version.  I found than rather to find Paypal.Api, inside there's something called Paypal.Core which has several classes, like PayPalHttpClient() and AccessToken(), the problem is... how to use them? any example on how to get the token? I been searching to see if I can get these specific workds on the net but nothing yet :-(

**Comment by mikaey** [comment]
Hi @sipi41,

If you're getting basic errors about namespaces not being recognized, it sounds like maybe you're not installing the SDK correctly or missing a dependency.  I'd recommend using NuGet to install the SDK -- NuGet will make sure that the SDK (and any of its dependencies) get installed into your project.  If you're using Visual Studio 2017 or newer, NuGet should be automatically included; if not, you can get it from https://www.nuget.org/downloads.  (I'm using Visual Studio 2017, so my instructions will assume you are as well.)

Next, go to Tools->NuGet Package Manager->Manage NuGet Packages for Solution.  Click on the "Browse" tab, and search for PayPal.  (Make sure to click the "Include prerelease" checkbox, otherwise you'll get vesion 1.9.1.)  Look for "PayPal by PayPal" and click on that.  On the right side of the window, click the checkbox for your solution, make sure version is set to "Latest prerelease 2.0.0-rc2" (or whatever is newest -- that's the newest version at the time I'm writing this), then click "Install".  When the "Preview Changes" window comes up, click OK.  NuGet will download the SDK and all of its dependencies and install them in your project.

Can you try that and let us know if that fixes things?  (I'm working on a code sample for you -- if using NuGet to install the SDK doesn't fix things, let me know and I'll get it posted.)

**Comment by sipi41** [comment]
Hey Mikaey, thanks for your reply... yes, I took the steps you mentioned, and successfully installed Paypal (2.0.0-rc2), in fact, with a try-fail approach I have created a token, now what should I do with it?  There's no documentation on that... please take a look to my console code:

[ConsoleCode.txt](https://github.com/paypal/PayPal-NET-SDK/files/2014144/sample.txt)

The problem is that I was unable to find any documentation on methods like AccessTokenRequest() or PaypalHttpClient() or the method Execute<AccessTokenRequest> etc... 

**Thank you** again for your help and patience, after all this, I hope to publish a video or something on what I did so I can help others...

**Comment by mikaey** [comment]
Excellent!  So the good news is that you managed to get an access token; the bad news is that you didn't need to get one -- the SDK will manage that for you. :smile:

So...my example code is below.  This is modified from [the example that's in the README](https://github.com/paypal/PayPal-NET-SDK/blob/2.0-beta/README.md) (which apparently isn't 100% right).  I know this isn't a perfect example, but hopefully this will get you moving in the right direction.

Note that the general process is as follows:
1. Create the payment (which my example code does)
2. Send the buyer over to PayPal (my example code shows them a link to the PayPal site; you'll want to use a redirect or something like [Smart Payment Buttons](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/))
3. Wait for the buyer to get done on PayPal
4. Optionally -- [get the details on the buyer](https://developer.paypal.com/docs/api/payments/#payment_get) (this gives you a chance to import the buyer's shipping address from PayPal, so that they don't have to enter it on your site)
5. [Execute the payment](https://developer.paypal.com/docs/api/payments/#payment_execute) (remember -- no money moves until you make this call!)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using PayPal.Core;
using PayPal.v1.Payments;

namespace DotNetSDK20Example
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Run(async (context) =>
            {
                var environment = new SandboxEnvironment("(replace with your client ID)", "(replace with your secret)");
                var client = new PayPalHttpClient(environment);

                var payment = new PayPal.v1.Payments.Payment()
                {
                    Intent = "sale",
                    Transactions = new List<Transaction>()
                    {
                        new Transaction()
                        {
                            Amount = new Amount()
                            {
                                Total = "10",
                                Currency = "USD"
                            }
                        }
                    },
                    RedirectUrls = new RedirectUrls()
                    {
                        ReturnUrl = "https://www.example.com/",
                        CancelUrl = "https://www.example.com"
                    },
                    Payer = new Payer()
                    {
                        PaymentMethod = "paypal"
                    }
                };

                PaymentCreateRequest request = new PaymentCreateRequest();
                request.RequestBody(payment);

                System.Net.HttpStatusCode statusCode;

                try
                {
                    BraintreeHttp.HttpResponse response = await client.Execute(request);
                    statusCode = response.StatusCode;
                    Payment result = response.Result<Payment>();

                    string redirectUrl = null;
                    foreach(LinkDescriptionObject link in result.Links)
                    {
                        if(link.Rel.Equals("approval_url"))
                        {
                            redirectUrl = link.Href;
                        }
                    }

                    if(redirectUrl == null)
                    {
                        // Didn't find an approval_url in response.Links
                        await context.Response.WriteAsync("Failed to find an approval_url in the response!");
                    } else
                    {
                        await context.Response.WriteAsync("Now <a href=\"" + redirectUrl + "\">go to PayPal to approve the payment</a>.");
                    }
                } catch(BraintreeHttp.HttpException ex)
                {
                    statusCode = ex.StatusCode;
                    var debugId = ex.Headers.GetValues("PayPal-Debug-Id").FirstOrDefault();
                    await context.Response.WriteAsync("Request failed!  HTTP response code was " + statusCode + ", debug ID was " + debugId);
                }
            });
        }
    }
}
```

**Comment by xiaoleih41** [comment]
Close the issue as it has been resolved.

**Comment by chuksgpfr** [comment]
Hi @xiaoleih41 i tried your code in my startup.cs and it worked, but it kept returning this error when i implemented in my controller. "the application completed without reading the entire request body."

Please Help

**Comment by chuksgpfr** [comment]
Thanks.. I solved it, i was adding ExperienceId before. That was why the error.
Does this have ExperienceId ?

**Comment by SuperChickenBurritos** [comment]
Hi @mikaey , how do I implement this into a controller?

**Comment by SuperChickenBurritos** [comment]
@chuksgpfr Did you find how to execute a payment?

**Comment by geno333** [comment]
@mikaey  I see that this was almost two years ago that you replied to this thread, but I'm hoping that you're still out there and can help me with a question about the code you provided.
What you gave for as a .net core code example worked Great, THANKS!  
But now that i can create a working payment transaction, how to i get the payee's information?  I've poked around in the dark hoping to stumble onto something but i'm at wits end.
