### ISSUE TITLE
Your documentation is misleading about Checkout V2

### ISSUE THREAD

**Issue by jamie-tillman** [paypal/PayPal-NET-SDK#425]
Your main documentation page mentions that integrating with Checkout V2 requires use of another project rather than this one, and that this project is being deprecated.  However, you seem to have some confusion about what this new project actually supports.

The project you direct users to is currently only set up for DotNetCore and has zero documentation for use with .NET Framework.  If you're going to completely abandon .NET Framework, you should be explicit with this to avoid confusion -- and those of us using .NET framework will apparently have to look elsewhere.

**Comment by eqcb** [comment]
I have to agree with Jamie. And oh boy, this is going to be a big post.
I'm starting a business and I chose(but probably wont stick with due to this mess) Paypal to be able to monetize quickly. 
The documentation on the developer domain (developer.paypal.com) is spread all over the place. I simply want to add the .net SDK to my back-end to capture transactions for all the purposes needed to run a business but, while the docs say to me to use "dotnet add package" I cant use it because my project is not on .net Core. **There is no mention what so ever about SDK and .net Core anywhere there thought**

On the bottom of this page(https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/) there's a link to additional information for .net that leads to the checkout SDK(https://github.com/paypal/Checkout-NET-SDK/) that states:

> This is a **part** of the next major PayPal SDK. It includes a **simplified** interface to **only** provide simple model objects and blueprints for HTTP calls. This repo currently contains functionality for PayPal Checkout APIs which includes Orders V2 and Payments V2.

Is this "part of the next update" what I'm suposed to use on my back-end? Is it even reliable?
And also:

> Please refer to the PayPal Checkout Integration Guide for more information. Also refer to Setup your SDK for additional information about setting up the SDK's.

With a link that goes back to the setup-sdk link! Making this a loop!
To add to this the prerequisites include: ".NET 4.6.1 or later". (?!)

The latest thing I've found that was made for full .Net framework haven't seen an update in 2 years! And that's the **PayPal-NET-SDK** that its said to be deprecated in favor of checkoutv2 with is the "part of the next major update" as above.

So, two questions out of this:
For back-end stuff like confirming and saving transactions, etc I should download and add the checkout SDK to my solution?
Is it going to be .net core only? Will everyone have to refactor their code base for this?

Please help before I give up on this.. almost two days learning the flow of transactions and trying to figure out the what/how I should use.

**Comment by jamie-tillman** [comment]
Considering my ticket has sat here for more than a month without even a blip, I feel no qualms saying that if the dev team for this project is looking for an example of doing it right, check Stripe's documentation and approach.  (And that's a not-so-subtle suggestion for @ecqb, too, if they are looking for an alternative platform that maintains a good API)

**Comment by liguob666** [comment]
准备使用.net集成，但是没有找到合适的例子，联系了客服也只是给我了一个网页地址，并没有得到任何实际的帮助

**Comment by sucithrashanu** [comment]
@jamie-tillman 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) 

Thanks!

**Comment by jamie-tillman** [comment]
I think the response to this ticket (and abrupt closure) may be indicative of the attitude and lack of understanding we can expect from this team.  I wasn't asking when v2 was going to be released.  I was pointing out a flaw in the documentation that will be a consistent time-waster for anyone trying to use .NET Framework to integrate with PayPal.  

If you don't care to fix it, that's ok by me, but I'll just make it clear here that defects in documentation can be just as problematic as bugs in code and failing to fix them will reflect poorly on your project and your team.  Best of luck to you.

**Comment by prakash-gangadharan** [comment]
Hi @jamie-tillman here the intention is not to close the issue abruptly. we advice you to reach [PayPal Community ](https://www.paypal-community.com)and  [MTS]( https://paypal.com/mts) for faster solution.

[PayPal Checkout v2](https://github.com/paypal/PayPal-NET-SDK#paypal-checkout-v2) 
The above doc clearly says if one need to integrate with  [v2/checkout/orders](https://developer.paypal.com/docs/api/orders/v2/) and [v2/payments](https://developer.paypal.com/docs/api/payments/v2/) APIs, obviously the newer endpoints. Please refer to the [Checkout .NET SDK](https://github.com/paypal/Checkout-NET-SDK) .

Its sounds more like about the end points rather than the framework.
