### ISSUE TITLE
SDK: Sale.Refund()

### ISSUE THREAD

**Issue by EdSF** [paypal/PayPal-NET-SDK#62]
Line 130 of [`Sale.cs`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/Sale.cs)
`var resourcePath = "v1/payments/sale/{0}/refund";`

`saleId` is missing/not set in `resourcePath`. 

This results a POST to: `https://api.sandbox.paypal.com/v1/payments/sale/%7B0%7D/refund`

Sample (via Fiddler):

    POST https://api.sandbox.paypal.com/v1/payments/sale/%7B0%7D/refund HTTP/1.1
    Content-Type: application/json
    User-Agent: PayPalSDK/PayPal-NET-SDK 1.2.0 (lang=DOTNET;v=4.5.1;clr=4.0.30319.34209;bit=64;os=Microsoft Windows NT 6.2.9200.0)
    Authorization: Bearer [the token]
    PayPal-Request-Id: d9f6d5ec-14e9-4553-bd8e-c2ac651cc8fc
    Host: api.sandbox.paypal.com
    Content-Length: 45
    Expect: 100-continue
    Connection: Keep-Alive

    {"amount":{"currency":"USD","total":"25.87"}}

**Comment by jziaja** [comment]
Thanks for spotting that @EdSF!  I'll get that fixed and add some (apparently missing) unit tests to ensure that's accounted for in the future.  Also, since that file is autogenerated by an internal tool, I'll double-check our tool to see why that method was generated incorrectly so it doesn't happen again in the future.

**Comment by EdSF** [comment]
Cool beans @jziaja :) I'm `new`ing up those methods for now :) Thanks!
