### ISSUE TITLE
Error when trying to make Direct Payment with Maestro card

### ISSUE THREAD

**Issue by halimakoundi** [paypal/PayPal-NET-SDK#67]
I get an error when trying to make a direct payment with maestro card on sandbox account :

Exception:
````json
{
	"name": "VALIDATION_ERROR",
	"details": [{
		"field": "payer.funding_instruments[0].payment_card",
		"issue": "This field name is not defined for this resource type"
	}],
	"message": "Invalid request - see details",
	"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
	"debug_id": "beccd097d4f95"
}
````

I am not setting the issue number but the `start_month` and `start_year` for the `fundInstrument.payment_card` object.

Thanks for your help.

**Comment by jziaja** [comment]
Hi @halimakoundi, looking at the logs I see you're using version 0.11.0 of this SDK.  Are you able to upgrade to the current version 1.2.2 ([NuGet](https://www.nuget.org/packages/PayPal) or [GitHub direct download](https://github.com/paypal/PayPal-NET-SDK/releases)) and try it again?  Thanks!

**Comment by halimakoundi** [comment]
Hi @jziaja,

I updated the PaypalSDK as suggested , I do have now 
RestApiSDK 0.11.0.0
PaypalCoreSDK 1.6.0.0
Paypal 1.2.2.0

I still have the same issues, to be honnest I am quite confused as per which dll I do have to reference for the restApi ..

Thanks for your help.

**Comment by jziaja** [comment]
You do not need **RestApiSDK** and **PayPalCoreSDK** as the newer **PayPal** library replaces both of these.  I checked NuGet, and it looks like the message I added explaining the replacement on the **PayPal** package got removed during a previous publish; I'll add that explanation back in so it's clear.

Also, because the newer library now includes the Core SDK, some changes needed to be made with the namespacing to avoid namespace conflicts.  [Refer to this section of the readme](https://github.com/paypal/PayPal-NET-SDK#upgrade-instructions) for help regarding the upgrade process (it's mostly just replacing `using` declarations).

**Comment by jziaja** [comment]
Hi @halimakoundi , were you able to get the library working with your project?  If you're still experiencing the problem you mentioned, would you mind sharing how you have your Payment object setup for making the direct payment with the maestro card?  Thanks!

**Comment by halimakoundi** [comment]
Hi,
Thanks for your help and explanations.
I still have the same issue.
see here the dll is Paypal.dll version 1.2.2.0 (the latest)
![image](https://cloud.githubusercontent.com/assets/5450688/5879233/45a30220-a325-11e4-9c53-30c96afa7197.png)

And I have error message as below 
{"name":"VALIDATION_ERROR","details":[{"field":"payer.funding_instruments[0].payment_card","issue":"This field name is not defined for this resource type"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"667366c8bd159"}

is my code wrong ?

   Dim credtCard As New CreditCard()
        credtCard.type = cardType
        credtCard.number = "xxxxxxxxxxxxxxxxxx"
        credtCard.cvv2 = "653"
        credtCard.expire_month = 10
        credtCard.expire_year = 2017
        credtCard.first_name = "Design"
        credtCard.last_name = "TestPerso"

        Dim fundInstrument As New FundingInstrument()


        Dim billingInfo As New Address()
        billingInfo.city = "London"
        billingInfo.country_code = "GB"
        billingInfo.line1 = "8 Glenthorn Mews"
        billingInfo.postal_code = "W6 0LJ"

        Dim payerInfo As New PayerInfo()
        payerInfo.billing_address = billingInfo
        payerInfo.email = "test@sandbox.co.uk"
        credtCard.billing_address = billingInfo


        '**Handling Maestro paiement
        If cardType = "maestro" Then
            Dim paymtCard As New PaymentCard()
            paymtCard.billing_address = billingInfo
            paymtCard.start_month = 9
            paymtCard.start_year = 2014
            paymtCard.type = cardType
            paymtCard.number = "xxxxxxxxxxxxxxxxxxxxxx"
            paymtCard.cvv2 = "xxx"
            paymtCard.expire_month = 10
            paymtCard.expire_year = 2017
            paymtCard.first_name = "Design"
            paymtCard.last_name = "TestPerso"

            fundInstrument.payment_card = paymtCard
            fundInstrument.credit_card = credtCard '## When I remove this line I have an Internal Server error as a response from the api
        Else
            fundInstrument.credit_card = credtCard
        End If


        Dim fundingInstrumentList As New List(Of FundingInstrument)()
        fundingInstrumentList.Add(fundInstrument)

        Dim payr As New Payer()
        payr.funding_instruments = fundingInstrumentList
        payr.payment_method = "credit_card"
        payr.payer_info = payerInfo

        Dim amnt As New Amount()
        amnt.currency = "GBP"
        amnt.total = amount.ToString("0.00")

        Dim tran As New Transaction()
        tran.description = "Design911 order number 149918"
        tran.amount = amnt

        Dim transactions As New List(Of Transaction)()
        transactions.Add(tran)

        Dim pymnt As New Payment()
        pymnt.intent = "sale"
        pymnt.payer = payr
        pymnt.transactions = transactions

        Return pymnt

If sdkConfig.Count = 0 Then sdkConfig.Add("mode", "sandbox")
        If String.IsNullOrEmpty(accessToken) Then Throw New PaypalPaymentException("Token is mandatory")
        Dim apiContext As New PayPal.Api.APIContext(accessToken)
        apiContext.Config = sdkConfig
        Try
            Dim createdPayment As Payment = payment.Create(apiContext)
            Return createdPayment
        Catch ex As PaymentsException
            Throw New PaypalPaymentException(ex.Message & " " & ex.Response)
        Catch ex As System.Exception
            Throw New PaypalPaymentException(ex.Message)
        End Try

**Comment by halimakoundi** [comment]
Screenshot of the Internal server error 

![image](https://cloud.githubusercontent.com/assets/5450688/5879403/e936a8aa-a326-11e4-8042-9b7bdc891002.png)

If you could provide me with a test example of maestro payment it would be very helpful !
Thanks a lot for your help !!

Cheers.

**Comment by halimakoundi** [comment]
Also,

I understand that for maestro payments, we need to provide either an issue number or start and end date for the payment card , but there is no such field as issueNumber or similar in the object PayPal.Api.CreditCard nor in the object PayPal.Api.PaymentCard

Thanks.

**Comment by jziaja** [comment]
Thanks for the detailed information @halimakoundi!  I'm currently looking into this and will get back to you once I have more information.

**Comment by halimakoundi** [comment]
Thanks a lot

**Comment by jziaja** [comment]
Sorry for the delay.  Unfortunately, payments using Maestro cards aren't yet possible using the REST API.  You'll have to use the Classic SDK until that support gets added to REST payments.

Using the [PayPal Merchant SDK for .NET](https://github.com/paypal/merchant-sdk-dotnet) (available on [NuGet](https://www.nuget.org/packages/PayPalMerchantSDK/)), you can call [DoDirectPayment](https://developer.paypal.com/docs/classic/api/merchant/DoDirectPayment_API_Operation_NVP/) with the Maestro card details.  If you look at that documentation page for the call, you'll see it has a note that confirms what you were expecting:

> If the credit card type is `Maestro`, you must set `CURRENCYCODE` to `GBP`. In addition, you must specify either `STARTDATE` or `ISSUENUMBER`.

Hope that helps, and let me know if you encounter any issue trying to work with the Merchant SDK.

Also, regarding the error you're seeing about `payment_card` not being defined, this is related to Issue #58 in that the `FundingInstrument` class currently contains properties that aren't actually publicly available yet (the root cause of this issue was found internally and a new strategy is being worked on to help avoid these types of properties leaking early).  The SDK team is currently working on identifying these properties, and I will be marking them as **obsolete** in future builds of this SDK to help avoid confusion in using them.  Once the fields are properly supported, I'll remove the obsolete attribute.

**Comment by halimakoundi** [comment]
Hi Thank you for your return..
I have done some tests with the merchant sdk and seem to work fine on the sandbox

Where can I subscribe to know when the Maestro become supported on Rest API ?
Cheers.

**Comment by jziaja** [comment]
The best way would be to follow this repository here on GitHub.  As soon as support gets added, it'll likely require changes to the model objects in this SDK to support the fields required (`STARTDATE`, `ISSUENUMBER`, and anything else) for making Maestro payments.
