### ISSUE TITLE
How do I complete a payment transaction after PayPal redirects to my page?

### ISSUE THREAD

**Issue by darkducke** [paypal/PayPal-NET-SDK#79]
Hello, create a transaction and can redirect the user to the paypal page, but to complete the transaction, paypal redirects again to my page returning "guid=28&paymentId=PAY-1JA4888378933470CKTOK3EY&token=EC-1DB245768R4006834&PayerID=8G5NCSXGQ4E5Q" But is not generated any transaction in paypal, or the seller's account or the account the buyer, sandbox accounts, what's wrong? missing some step?

code:
````csharp
var payer = new Payer() { payment_method = "paypal" };

var details = new Details()
{
    tax = "0",
    shipping = "0",
    subtotal = strTotalPedido
};

// ###Amount
// Let's you specify a payment amount.
var amount = new Amount()
{
    currency = "BRL",
    total = strTotalPedido, // Total must be equal to sum of shipping, tax and subtotal.
    details = details
};

var transactionList = new List<Transaction>();

transactionList.Add(new Transaction()
{
    description = "Produtos",
    invoice_number = nCodPed,
    amount = amount,
    custom = nCodPed,
    item_list = itemList
});


var payment = new Payment()
{
    intent = "sale",
    payer = payer,
    transactions = transactionList,
    redirect_urls = redirUrls
};

var createdPayment = payment.Create(apiContext);

var links = createdPayment.links.GetEnumerator();
while (links.MoveNext())
{
    var link = links.Current;
    if (link.rel.ToLower().Trim().Equals("approval_url"))
    {
        xLinkRedirPP = link.href;
    }
}
HttpContext.Current.Session.Add(guid, createdPayment.id);

HttpContext.Current.Response.Redirect(xLinkRedirPP);
````

**Comment by jziaja** [comment]
Hi @darkducke, great question! The last step you're missing is [executing the payment](https://developer.paypal.com/docs/integration/web/accept-paypal-payment/#execute-the-payment). :)

An example of this can be found in the [PaymentWithPayPal.aspx.cs](https://github.com/paypal/PayPal-NET-SDK/blob/master/Samples/Source/PaymentWithPayPal.aspx.cs#L144) file in the sample project.

Here's a slight modification of the sample code to do the payment execution:
````csharp
// Using the information from the redirect, setup the payment to execute.
var paymentExecution = new PaymentExecution() { payer_id = Request.Params["PayerID"] };
var payment = new Payment() { id = Request.Params["paymentId"] };
                
// Execute the payment.
var executedPayment = payment.Execute(apiContext, paymentExecution);
````

**Comment by jziaja** [comment]
Doh, I forgot I updated the `Execute()` method with a static call option in a previous release, which would shorten the sample code from my previous reply slightly:

````csharp
// Using the information from the redirect, setup the payment to execute.
var paymentExecution = new PaymentExecution() { payer_id = Request.Params["PayerID"] };
                
// Execute the payment.
var executedPayment = Payment.Execute(apiContext, Request.Params["paymentId"], paymentExecution);
````

I imagine most merchants making this call are simply just needing to execute the payment using the provided `PayerID` and are not interested in overriding the `amount` or `shipping_address` associated with the payment (which is what the `PaymentExecution` object allows for).  For that reason, I may consider adding another static `Execute()` method that just takes a `PayerID` value instead of a `PaymentExecution` object.  That would simplify the above code to the following:

````csharp
var executedPayment = Payment.Execute(apiContext, Request.Params["paymentId"], Request.Params["PayerID"]);
````

**Comment by darkducke** [comment]
Thanks for the help, is now generating transactions, plus the status is "pending", I used paypal balance, should not complete?
I do anything else to approve the customer's request and change the status?

thanks again!!! ;)

**Comment by jziaja** [comment]
Sometimes processing the payment can take a bit, but it should only be a matter of seconds at most if you're using your PayPal balance.  Does the payment still show as `pending`?  If it does, it could be that you have payment review enabled on your account.  If you have one of the transaction IDs handy then I can look it up and verify if that's the case.

**Comment by darkducke** [comment]
Transaction ID: 32W337694S572243U

**Comment by jziaja** [comment]
Your transactions are going into [Payment Review](https://www.paypal.com/sg/webapps/mpp/security/sell-paymentreview).  In order to disable this, you will need do the following:

  1. Login to your [Developer Dashboard](https://developer.paypal.com/webapps/developer/applications/myapps)
  2. Click on **Accounts** under the _Sandbox_ heading
  3. Expand the facilitator account and click **Profile**
  4. Click the **Settings** tab
  5. Click the **Off** button under _Payment review_

![image](https://cloud.githubusercontent.com/assets/8227966/6175257/b077b63c-b2ba-11e4-85ec-22e38cfb5339.png)

**Comment by darkducke** [comment]
Thank you so much, your help was very helpful to me!
