### ISSUE TITLE
ECheck Payments

### ISSUE THREAD

**Issue by prashant-anand** [paypal/PayPal-NET-SDK#81]
Does the REST API support Electronic Check Payments? I combed through the entire code and found only couple of references to ECheck.

**Comment by jziaja** [comment]
Hi @prashant-anand, unfortunately no, e-checks are not currently supported in the REST API.

Also, see my response in [Issue #58](https://github.com/paypal/PayPal-NET-SDK/issues/58#issuecomment-69363651) regarding why this and some other unsupported funding instruments made their way into the .NET codebase.

**Comment by prashant-anand** [comment]
Ok Thanks for the prompt response.

**Comment by prashant-anand** [comment]
Would be nice to know when the API can handle Electronic Check Payments as it is a very important form of payment for us.

**Comment by jziaja** [comment]
Wow, I apologize, @prashant-anand  - I misinterpreted the question and was thinking of a non-PayPal-linked bank account at the time I answered this question.

The correct answer is **yes, eChecks are supported** since they're done by using a bank account that is linked to your PayPal account.  The `payment_method` will be `paypal` for these types of payments, and the buyer can choose to use their PayPal balance or linked credit card or bank account.

If an eCheck is used to complete the payment, the `state` of the transaction may remain as `pending` until the check clears with the bank (typically a [few days](https://www.paypal.com/us/webapps/helpcenter/helphub/article/?solutionId=FAQ1082&topicID=&m=ARA)).  Also, the `clearing_time` will be set to give you an indication of when the check should clear with the buyer's linked bank account.  See the documentation for the [`sale`](https://developer.paypal.com/docs/api/#sale-object), [`authorization`](https://developer.paypal.com/docs/api/#authorization-object), or [`order`](https://developer.paypal.com/docs/api/#order-object) objects on PayPal Developer for more information.

**Comment by prashant-anand** [comment]
When i say Electronic Checks what i really mean is ACH payments where a buyer is using a bank routing and account information to transfer money to the merchant in lieu of using a Credit Card. Is what you are describing above the same?

**Comment by jziaja** [comment]
OK, so maybe I wasn't off with my original answer! :)  Currently, using a bank routing and account number (outside the context of a PayPal account) is not supported.  The Payments API team also has no guidance to provide on if or when this support might come.

The only currently-supported method of making a payment via the REST API using a bank account is if that account is linked to a PayPal account and the payment is done using that PayPal account.

**Comment by jziaja** [comment]
Closing - feel free to reopen if you have any other questions concerning eCheck payments or need further clarification on anything.

**Comment by hbhimanathi** [comment]
Is echeck option still not available ? The scenario is I dont want the user to go paypal site but give the user an ability to choose bank account and give the bankaccount number and routing number and the details and post the payment. Is this feature available in c#

**Comment by tomwhipple** [comment]
The best way to advocate for API support is via a [merchant support request](https://www.paypal-techsupport.com/app/ask).
