### ISSUE TITLE
Get Changed Shipping Address w. Invoicing

### ISSUE THREAD

**Issue by tiffaa** [paypal/PayPal-NET-SDK#85]
Hello,

i'm using the Invoice API to send invoices to customers. Sending the invoices works fine, and after the customer had paid the invoice, i can check for payments with

```c#
Invoice i = Invoice.Get(apiContext, invoiceId)
Capture c = Capture.Get(apiContext, i.payment_details[0].transaction_id);
```

This works very well, but my problem is: 
If the customer changes his shipping address within the payment process, how can retrieve the new shipping address? With `Invoice.Get`, the invoice object still holds the old shipping address.
Moreover, there is no indication in the invoice or capture object, that the shipping address has changed.

Is there any way to get the 'new' shipping address?
Thanks in advance.

**Comment by tiffaa** [comment]
Quick update: if i use `Payment.Get(apiContext), transactionId)`, i get this error:

```
{"name":"INTERNAL_SERVICE_ERROR",
"message":"An internal service error has occurred",
"information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
"debug_id":"4e230c58e883c"}
```

**Comment by jziaja** [comment]
Hi @tiffaa , thanks for reporting this behavior!  

I'm testing this out on sandbox, and I'm seeing some really odd behavior by the API.  Along with **not** seeing any mention anywhere of the new shipping address in either the `Invoice` or `Capture` resource, I'm also seeing the following:

1. `Invoice.Get()` for a `PAID` invoice returns the associated payments in a JSON element titled **"payments"** instead of the expected **"payment_details"**.  

  It looks like this element was [renamed recently](https://developer.paypal.com/docs/api/#common-invoicing-objects) and the SDK may need to be updated.  However, can you confirm if you're seeing **"payment_details"** from the live service?  If the `payment_details` property on the `Invoice` object is being set, then the answer to that is likely 'yes', but I just want to confirm.

2. The transaction being reported by the API is completely incorrect.

````json
"payments": [{
    "type": "PAYPAL",
    "transaction_id": "6BW19789BX1352237",
    "transaction_type": "SALE",
    "method": "PAYPAL",
    "date": "2015-03-06 05:30:25 PST"
}]
````

  If I do a `Sale.Get()` using that transaction ID, I get a `404 Not Found` error.

  If I do a `Capture.Get()` using that transaction ID, it **works** and returns the following capture details:

````json
{
	"id": "3NX5104778729280T",
	"create_time": "2015-03-06T13:30:24Z",
	"amount": {
		"total": "500.00",
		"currency": "USD"
	},
	"state": "completed",
	"links": [{
		"href": "https://api.sandbox.paypal.com/v1/payments/capture/3NX5104778729280T",
		"rel": "self",
		"method": "GET"
	},
	{
		"href": "https://api.sandbox.paypal.com/v1/payments/capture/3NX5104778729280T/refund",
		"rel": "refund",
		"method": "POST"
	}]
}
````

  There's a couple obvious problems with this.  First, the ID stored in the resource **does not** match with the ID of the resource in the URL.  This does not align with RESTful principles, as far as I'm aware, and I'll be reporting this to the API team as a bug.

  Second, the `transaction_type` is defined as `SALE` in the invoice; whereas the actual resource is a **Capture** resource.  This is both confusing and misleading.

---

Regarding the error you're receiving from calling `Payment.Get()`.  This is a known error when looking up a payment using an invalid ID.  The ID you're using is a transaction ID, not a payment ID.  Thus, it will need to be looked up using a `Sale.Get()`, `Capture.Get()`, `Authorization.Get()`, or `Order.Get()` (basically any `*.Get()` using a transaction object).

I'll forward this qustion to the API team to see if we can get clarification on how to properly handle the case of a buyer changing their shipping address while making a payment.  As soon as I hear back from them, I'll let you know.

Thanks again for reporting this!

**Comment by jziaja** [comment]
Quick update: I've escalated these issues internally.  The (PayPal-internal) ticket numbers are the following:

* **SRE-28278**: `invoice.payment_details` renamed to `invoice.payments`, and, `invoice.refund_details` renamed to `invoice.refunds` in an already-released API.  This breaks existing integrations as developers expect that critical information to be included in those pre-existing properties.  Pre-existing properties must be supported throughout the life of the v1 services and should only be unsupported when moving to future versions.

* **SRE-28280**: Invoice transaction details are incorrectly marked, and associated transaction ID does not match the actual resource ID.

Our team considers both of these issues to be of major severity, so we're pushing to get a response from the API team ASAP.

Regarding the question about the changed shipping address, I've reached out to the API team and am awaiting a response.

**Comment by tiffaa** [comment]
First of all,

thank you very much for your quick response!

When i do a `Invoice.Get(apiContext, "INV2-FSLE-L4EN-B8TM-NBRV")` i get this JSON response (i'll post just the interesting stuff)

```JSON
{
   "id":"INV2-FSLE-L4EN-B8TM-NBRV",
   "number":"AU11601",
   "status":"PAID",
   "merchant_info":{ },
   "billing_info":[ ],
   "shipping_info":{ },
   "items":[ ],
   "invoice_date":"2015-03-05 PST",
   "payment_term":{
      "term_type":"DUE_ON_RECEIPT",
      "due_date":"2015-03-05 PST"
   },
   "tax_calculated_after_discount":false,
   "tax_inclusive":false,
   "terms":"ProformaRechnung",
   "total_amount":{
      "currency":"EUR",
      "value":"773.40"
   },
   "payments":[
      {
         "type":"PAYPAL",
         "transaction_id":"5R428743HL851660Y",
         "transaction_type":"SALE",
         "date":"2015-03-05 06:41:10 PST",
         "method":"PAYPAL"
      }
   ],
   "metadata":{ }
}
``` 
However, in .NET the **"payments"** are stored in **"paymentDetails"**, because of this property:

```csharp
[JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "payments")]
public List<PaymentDetail> payment_details { get; set; }
```
So the **"paymentDetails"** look like this: 

![paypal](https://cloud.githubusercontent.com/assets/11348736/6527343/5567bc76-c41a-11e4-8c88-7badb1cecd65.PNG)

Now i do `Capture.Get(apiContext,"5R428743HL851660Y")` and i get the capture.

```JSON
{
   "id":"6YY01603K6645840X",
   "amount":{
      "currency":"EUR",
      "total":"773.40"
   },
   "state":"completed",
   "create_time":"2015-03-05T14:41:10Z",
   "links":[
      {
         "href":"https://api.sandbox.paypal.com/v1/payments/capture/6YY01603K6645840X",
         "rel":"self",
         "method":"GET"
      },
      {
         "href":"https://api.sandbox.paypal.com/v1/payments/capture/6YY01603K6645840X/refund",
         "rel":"refund",
         "method":"POST"
      }
   ]
}
```
This looks O.K. to me (*6YY01603K6645840X* is the transaction code Paypal is showing in my account and the amount is in both cases €773,40 EUR)

Hope I could help.

**Comment by jziaja** [comment]
Are you using a forked or custom version of this SDK?  The [current code for the Invoice object](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/Invoice.cs#L138) maps the `payment_details` property to a "payment_details" JSON element.

While it's great that code fix works, it's still a problem because the API should never change a field like that on a released version.  Or if they do, they need to continue supporting the older field along with the newer one.  While the PayPal SDKs can be quickly updated to support this change, it means that anyone currently using invoices with any of the SDKs have a broken version and must update to fix that support.  Definitely not a good developer experience and goes against any sort of developer-first initiative. :(

**Comment by tiffaa** [comment]
I'm using the latest compiled(!) `paypal.dll` from the SDK.

**Comment by jziaja** [comment]
Hi @tiffaa, the Invoicing API team has unfortunately indicated that this behavior is something they do not plan to address in the current version of the API.  The team did say they would support this in their next version; however, there is currently no ETA on when to expect the next version of the API.

In the meantime, I'm going to work with the docs team to see if we can add some sort of disclaimer on the [PayPal Developer Invoicing documentation](https://developer.paypal.com/docs/integration/direct/invoicing/) so developers & merchants are aware of this limitation well in advance.
