### ISSUE TITLE
APIContext.RequestId and DUPLICATE_REQUEST_ID errors

### ISSUE THREAD

**Issue by Jaans** [paypal/PayPal-NET-SDK#89]
Efficient resource usage would suggest a design that creates a single `APIContext` instance and reusing that until the contained OAuth `AccessToken` expires, at which point a refreshed `AccessToken` is obtained and then used to create a new instance of `APIContext`.

This approach works well for us, but we are seeing ***`DUPLICATE_REQUEST_ID`*** errors where the `PayPal-Request-Id` header used for idempotency, is not unique with every request (as it should be).

Currently, The .NET SDK automatically uses the `APIContext.RequestId` property value to set the `PayPal-Request-Id` request header, and the `APIContext` would've initialised it's `RequestId` property with a new `GUID`. 

If our design was such that we were to create a new instance of the `APIContext` for every API call, then that would result in unique `RequestId`'s for every API call, but it would not if the `APIContext` instance is reused (like we do).

There was a similar issue with the PHP version of the SDK, and their solution there was to add a method to the `APIContext` called `ResetRequestId` (or it could be just plain `Reset`) that prepares the `APIContext` instance to be reused, for example by assigning a new `GUID` value to the `RequestId` property. Refer lines 75-86 from the PHP source [here](https://github.com/paypal/PayPal-PHP-SDK/blob/bbef3664c5285c19f9770176817bfaf5015abf7c/lib/PayPal/Rest/ApiContext.php)

We're not fussed about how the `RequestId` is reset (i.e. whether explicitly through a call to `Reset` or implicitly by the SDK after it's used in a SDK call), but would really appreciate the ability to retain a resource efficient design that can reuse the `APIContext` instance. Please can you add support for resetting the `RequestId` value (either implicit or explicit).

Thanks!

**Comment by jziaja** [comment]
:+1: Thanks for the request, @Jaans , and I completely agree that this functionality should be available in this SDK.  I'll see if I can work this improvement into the next release (1.5).

**Comment by Jaans** [comment]
Thanks! that'll be great. 
Any idea on the timings of the 1.5 release?

**Comment by jziaja** [comment]
It will likely be a week or two after I get 1.4.1 officially released, which should be happening any day (just waiting to hear back from a specific merchant to see if the fixed compatibility issue with the Classic SDKs has been resolved).

**Comment by Jaans** [comment]
Hi Jason

Just following up. Noticed 1.4.1 released earlier. Do you think we might see this released by the week of 11 May 2015?

Let me know if I can assist.
Thanks

**Comment by jziaja** [comment]
@Jaans I'm currently working on the 1.5 release and plan to get this fix add very soon.  You're more than welcome to submit a pull request with the fix if you'd like to have it added sooner.  As for a timetable, the best I can give you is that we'll hopefully be able to provide a release in the next couple weeks.  The main feature for 1.5 is Webhook event validation, for which the code is mostly ready in a private branch, but there's a few security details our team is still working out.

If adding Webhook event validation takes longer than expected, I'll consider doing a 1.4.2 release sooner that includes the fix for this issue.  Regardless, I'll keep you posted. :+1:

**Comment by jziaja** [comment]
@Jaans I added a new [`ResetRequestId()`](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/APIContext.cs#L82) method to `APIContext` (along with cleaning up the properties a bit and adding/fixing the XML comments).  I opted to call it "ResetRequestId()" instead of "Reset()" to avoid potential confusion regarding whether or not all the properties of `APIContext` would be reset.

Feel free to give the new code a try, and let me know how it works for you.

**Comment by Jaans** [comment]
@jziaja Thank you for that - makes perfectly sense. I had a look its good. Thanks again - I'm able to work with that. Are you thinking of a 1.4.2 release now instead?

**Comment by jziaja** [comment]
@Jaans sorry for the delay in responding. 1.4.2 was just released and includes this fix.  :+1:

**Comment by Jaans** [comment]
Thank you for this!
